### PR TITLE
update kguibout

### PR DESCRIPTION
**Pull request by thboura**

### CODE REVIEW

**Comment by alexandregv** [comment]
Why are you updating someelse songs ?

**Comment by thboura** [comment]
Students are doing this since the beginning of this feature, where is the problem ?
And the fact that I’m the one updating it is because my friend told me to.

**Comment by alexandregv** [comment]
Students are doing this since the beginning and it's still an abuse.

**Comment by thboura** [comment]
Great. So since I’m not a tutor anymore (so don’t have a free pass), and a private message from a staff telling me I can is not valid anymore, I’ll have to buy it once more ?
Wow.

**Comment by alexandregv** [comment]
You have to buy the Hall Voice on the intra shop to use it, yes.
If you buy it but gift it to someone, then it belongs to this person, not both of you.

**Comment by thboura** [comment]
So you’re dodging the question of special cases and blaming me, even if it’s not written anywhere.
Delete my songs then. Have been using them since 2018, must have been too much time I suppose.

**Comment by alexandregv** [comment]
I don't get which question I dodge. You want us to write the definition of a gift on the intra shop ?

**Comment by thboura** [comment]
I will send you a private message about all the problem there is in the current system at the right time and place.
It’s Sunday, and even if I’m a little mad, there should be more urgent business with other students (and once again, if you have to settle this immediately, remove my songs) :)

**Pull request closed without merging**
